language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

sudo: false

branches:
  except:
    - gh-pages

script:
  - npm run test-coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
